export const discordFacts: string[] = [
  "Discord was originally designed to be a communication tool for gamers.",
  "Discord's logo is a game controller combined with a chat bubble.",
  "Discord was founded in 2015 by Jason Citron and Stanislav Vishnevskiy.",
  "Discord has over 150 million monthly active users as of 2021.",
  "Discord was valued at $7 billion in a funding round in December 2020.",
  "Discord was inspired by the communication tools used by online game communities.",
  "Discord started out as a platform for voice chat and evolved into a full-fledged communication tool for communities of all types.",
  "Discord allows users to create and join multiple servers, each with their own channels and settings.",
  "Discord has a built-in streaming feature that allows users to stream their gameplay or screen to others in their server.",
  "Discord has a built-in store where users can purchase games and other digital products.",
  "Discord's name was originally inspired by the word 'discordant', which means 'disagreeing or incongruous'.",
  "Discord has a wide range of customizations available, including custom emojis, themes, and bots.",
  "Discord has partnerships with various game developers and publishers to offer exclusive perks and benefits to users.",
  "Discord has a dedicated team of moderators and a Trust and Safety team to ensure that the platform remains safe and welcoming for all users.",
  "Discord has been used for various purposes beyond gaming, such as education, business, and online communities.",
  "Discord's Nitro subscription service offers users access to a range of perks, including higher quality screen sharing, animated emojis, and server boosts.",
];
