export const softwareFacts: string[] = [
  "The first computer program was written by Ada Lovelace in the mid-1800s.",
  "The first software bug was a real bug - a moth stuck in a Harvard Mark II computer in 1947.",
  "The first computer virus was created in 1971 and was called the 'Creeper' virus.",
  "The term 'open source' was first used in 1998 to describe software that is free and open for anyone to use and modify.",
  "The most popular programming language as of 2021 is JavaScript.",
  "The first website was created in 1991 by Tim Berners-Lee, who also invented the World Wide Web.",
  "The first programming language was Fortran, which was developed in the 1950s for scientific computing.",
  "The first version control system was called RCS (Revision Control System), and it was developed in the 1980s.",
  "The longest word you can type using only the top row of a QWERTY keyboard is 'typewriter'.",
  "The concept of object-oriented programming (OOP) was first introduced in the 1960s, but it wasn't widely adopted until the 1980s.",
  "The first text message was sent in 1992, and it was sent from a computer to a mobile phone.",
  "The first computer virus to cause widespread damage was the 'ILOVEYOU' virus, which infected millions of computers in 2000.",
  "The first computer programmer was a woman named Ada Lovelace, who wrote the first algorithm in the mid-1800s.",
  "The 'Hello, World!' program is a common introductory program in many programming languages.",
  "The first computer was invented in the 1940s, and it was the size of a large room.",
];