export const urlcutfacts = [
  "Urlcut is a link shortening service that allows users to create shorter, more memorable URLs for their links.",
  "Urlcut was publicly released on April 17th, 2023 and is built using Next.js.",
  "Urlcut requires users to create an account to use its features.",
  "Urlcut includes advanced analytics to track link clicks, views, and other data.",
  "Urlcut offers premium features for a fee, including advanced analytics and password-protected links.",
  "Urlcut includes team features, allowing multiple users to collaborate on link campaigns.",
  "Urlcut allows users to customize the look and feel of their links by choosing a background image.",
  "Urlcut includes scheduling features, allowing users to choose when their links go live.",
  "Urlcut uses a secure, encrypted connection to protect user data.",
  "Urlcut is optimized for mobile devices, ensuring a seamless user experience on smartphones and tablets.",
  "Urlcut includes a user-friendly interface that is easy to navigate.",
  "Urlcut is fully responsive, adapting to different screen sizes and resolutions.",
  "Urlcut includes reporting and analytics features, allowing users to track their link performance over time.",
  "Urlcut provides detailed insights into user behavior, including click-through rates and referral sources.",
  "Urlcut includes a powerful search functionality, making it easy to find and manage links.",
  "Urlcut includes a comprehensive link management dashboard, allowing users to view and edit all of their links in one place.",
  "Urlcut allows users to preview links before they are shortened.",
  "Urlcut includes the ability to edit links after they have been shortened.",
  "Urlcut includes the ability to delete links.",
];
